server:
  port: '8080'

spring:
  application:
    name: device-management
  datasource:
    username: sa
    url: jdbc:h2:file:~/algasensors-device-management-db;CASE_INSENSITIVE_IDENTIFIERS=TRUE;AUTO_SERVER=TRUE;
    driverClassName: org.h2.Driver
    password: '123'
  h2:
    console:
      #Permite acesso remoto
      enabled: 'true'
      settings.web-allow-others: 'true'
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      #Alterar para create-drop em caso de mudanca do schema
      ddl-auto: update
    show-sql: 'true'